"use client";

import { useState } from "react";
import useSWR, { useSWRConfig } from "swr";
import { Topbar } from "@/components/layout/Topbar";
import { AlertCard } from "@/components/alerts/AlertCard";
import { Card, CardBody } from "@/components/ui/Card";
import { api, fetcher } from "@/lib/api";
import { useRealtime } from "@/lib/useRealtime";
import type { Alert, Severity } from "@/lib/types";

const SEVERITIES: Severity[] = ["CRITICAL", "HIGH", "MEDIUM", "LOW"];

export default function AlertsPage() {
  const [severity, setSeverity] = useState<Severity | "ALL">("ALL");
  const query = severity === "ALL" ? "" : `?severity=${severity}`;
  const { data, isLoading } = useSWR<{ alerts: Alert[] }>(`/alerts${query}`, fetcher, { refreshInterval: 10000 });
  const { mutate } = useSWRConfig();

  useRealtime((event) => {
    if (event.type === "alert.created" || event.type === "alert.updated") mutate(`/alerts${query}`);
  });

  async function updateStatus(alert: Alert, status: Alert["status"]) {
    await api.patch(`/alerts/${alert.id}`, { status });
    mutate(`/alerts${query}`);
  }

  const alerts = data?.alerts ?? [];

  return (
    <div>
      <Topbar title="Alerts" description="Generated by the backend Threat Engine — see docs/ai-pipeline.md" />

      <div className="space-y-4 p-6">
        <div className="flex flex-wrap gap-2">
          <FilterChip active={severity === "ALL"} onClick={() => setSeverity("ALL")}>
            All
          </FilterChip>
          {SEVERITIES.map((s) => (
            <FilterChip key={s} active={severity === s} onClick={() => setSeverity(s)}>
              {s}
            </FilterChip>
          ))}
        </div>

        {isLoading && <p className="text-sm text-slate-500">Loading...</p>}
        {!isLoading && alerts.length === 0 && (
          <Card>
            <CardBody className="text-sm text-slate-500">
              No alerts yet. Alerts appear here once the AI pipeline (Phase 8-13) reports activity that
              crosses a threat threshold.
            </CardBody>
          </Card>
        )}

        <div className="space-y-3">
          {alerts.map((alert) => (
            <AlertCard key={alert.id} alert={alert} onStatusChange={(status) => updateStatus(alert, status)} />
          ))}
        </div>
      </div>
    </div>
  );
}

function FilterChip({
  active,
  onClick,
  children,
}: {
  active: boolean;
  onClick: () => void;
  children: React.ReactNode;
}) {
  return (
    <button
      onClick={onClick}
      className={`rounded-full border px-3 py-1 text-xs font-medium transition-colors ${
        active
          ? "border-blue-500/40 bg-blue-500/10 text-blue-300"
          : "border-surface-border bg-white/5 text-slate-400 hover:text-slate-200"
      }`}
    >
      {children}
    </button>
  );
}
